PauseInit();
col = global.pplayer;
maxmenucooldown = room_speed/8;
menucooldown = maxmenucooldown;
middlex = oCore.gui_width/2;
middley = oCore.gui_height/2;
pausestartx = middlex-16-8;
spacing = 16+8;
xscale = 1;
yscale = 1;
unselectedalpha = 0.5;
pause = 0;